### ISSUE TITLE
Bot doesn't remove duplicate items in basket

### ISSUE THREAD

**Issue by OliverOrd** [abayomi185/currys-pc-order-bot#4]
Hi,

I was just testing the latest release (0.0.4) and I noticed that the bot doesn't remove items from the basket if the quantity is greater than 1. This bug happens when "Collection in Store" is available but "Delivery" is not available

![image](https://user-images.githubusercontent.com/44840410/109641895-2a281b80-7b4a-11eb-9e6e-3daf37227ff5.png)

**Comment by abayomi185** [comment]
Hey, this is a scenario I haven't tested for. I'll use the laptop in the screenshot you sent to test and rectify it.

**Comment by OliverOrd** [comment]
Hi, This scenario was what I fixed in my Pull Request. It appears to remove items from the basket fine in this scenario on that build. Maybe it might help?

**Comment by abayomi185** [comment]
I have found the issue. I'll be improving the debug log too as I was very confused why it wouldn't reset the basket in this scenario. It turns out there's a dialog that doesn't pop up for "Collection in Store" so it attempts to click a button and fails. I've added a try catch block to line 126 if you want to test it out before I push the changes

**Comment by abayomi185** [comment]
The postcode search button element also changes. I'll sort this out too.

**Comment by OliverOrd** [comment]
Thanks. Ill test when the changes have been pushed

**Comment by OliverOrd** [comment]
Are you trying to fix the bot so it allows both delivery and collection to checkout?

I would suggest that the bot only try to checkout if delivery is available. If only collection is available then I think it should remove the item from basket and wait for delivery to become available

**Comment by abayomi185** [comment]
Oh cool. That would definitely make things easier. I was going to do the preliminaries if you wanted to implement collection purchases.

**Comment by OliverOrd** [comment]
I have been following these drops for quite a while and usually, the product becomes available for collection a couple of minutes before it becomes available for delivery. It's better to just wait for the delivery option to become available as it's highly unlikely it would be available for collection in a store near to you.

Plus it's less work to just focus on delivery :)
