### ISSUE TITLE
Feature Idea: Test Mode

### ISSUE THREAD

**Issue by OliverOrd** [abayomi185/currys-pc-order-bot#7]
Hi,

I think a great future could be a "Test Mode" as a parameter in the config.

When "Test Mode" is enabled, the bot tries to checkout as normal until it gets to the final payment screen. If the bot is able to click the final payment button successfully it reports that a test has been completed successfully but it doesn't actually press the button and spend any money. 

This would be great to make sure it works without having to buy things and cancel them afterward.

**Comment by abayomi185** [comment]
Hey Oliver

There's currently a config option called ```disable_purchase```, although this forces a halt at the basket and before checkout. Would you rather have it go to the payment page?

**Comment by OliverOrd** [comment]
I think it would be more useful to have it at the payment page. Also, I think it's important that the test is only successful if the payment button has been found and could be clicked successfully. This would be really great to know when running the bot on headless chrome

**Comment by OliverOrd** [comment]
I'll have a go at a making a fix

**Comment by OliverOrd** [comment]
Test mode is done. I submitted a pull request
